=== michalskop/data_standards/gazette_notice/json_schema/gazette-notice-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "http://localhost/michal/project/data_standards/gazette_notice/json_schema/gazette-notice-schema.json",
    "title": "Notice",
    "description": "A gazette notice",
    "type": "object",
    "properties": {
        "publisher": {
            "description": "The publisher of the notice",
            "$ref": "./entity.json"
        },
        "identifier": {
            "description": "The publisher's identifier for the notice, which may not be unique",
            "type": [
                "number",
                "string"
            ]
        },
        "url": {
            "description": "The URL of the notice, at which a human may verify the data",
            "type": "string",
            "format": "uri"
        },
        "media_type": {
            "description": "The media type of the URL resource",
            "type": "string"
        },
        "date_published": {
            "description": "The date of publication of the notice in the gazette",
            "type": "string",
            "format": "date"
        },
        "date_unpublished": {
            "description": "The date of unpublication of the notice from the gazette",
            "type": "string",
            "format": "date"
        },
        "creator": {
            "description": "The original creator/author of the notice.",
            "$ref": "./entity.json"
        },
        "summary": {
            "description": "A brief summary of the notice's content",
            "type": "string"
        },
        "about": {
            "description": "The content of the notice",
            "type": "object",
            "properties": {
                "classification": {
                    "description": "The type of the notice",
                    "type": "array",
                    "items": {
                        "$ref": "classification.json"
                    }
                },
                "body": {
                    "description": "The unstructured prose content",
                    "$ref": "#/definitions/body"
                },
                "locations": {
                    "description": "Locations affected by the notice",
                    "type": "array",
                    "items": {
                        "$ref": "address.json"
                    }
                }
            }
        },
        "subjects": {
            "description": "The entities that the notice is primarily about",
            "type": "array",
            "items": {
                "$ref": "./entity.json"
            }
        },
        "documents": {
            "description": "Additional documents",
            "type": "array",
            "items": {
                "$ref": "#/definitions/document"
            }
        }
    },
    "required": [
        "publisher",
        "identifier",
        "url"
    ],
    "definitions": {
        "document": {
            "title": "Document",
            "description": "Any document",
            "type": "object",
            "properties": {
                "url": {
                    "description": "The URL of the document",
                    "type": "string",
                    "format": "uri"
                },
                "media_type": {
                    "description": "The media type of the URL resource",
                    "type": "string"
                },
                "body": {
                    "description": "The content of the document",
                    "$ref": "#/definitions/body"
                }
            }
        },
        "body": {
            "title": "Body",
            "description": "The unstructured content",
            "type": "object",
            "properties": {
                "value": {
                    "description": "The content",
                    "type": "string"
                },
                "media_type": {
                    "description": "The media type of the content",
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "required": [
                "value"
            ]
        }
    }
}

=== michalskop/data_standards/gazette_notice/json_schema/examples/simple-plasy-stanoveni-prechodne-upravy-provozu.json
{
    "publisher": {
        "entity_type": "organisation",
        "entity_properties": {
            "name": "Město Plasy",
            "identifiers": [
                {
                    "identifier": "00258245",
                    "scheme": "IČ"
                }
            ]
        }
    },
    "identifier": "http://www.plasy.cz/urad-361/uredni-deska/zverejneni-stanoveni-prechodne-upravy-provozu-mistni-komunikace-lipova-1282.html",
    "date_published": "2017-06-14",
    "date_unpublished": "2017-06-30",
    "creator": {
        "entity_type": "organisation",
        "entity_properties": {
            "name": "Městský úřad Kralovice",
            "identifiers": [
                {
                    "identifier": "00257966",
                    "scheme": "IČ"
                }
            ]
        }
    },
    "summary": "Stanovení přechodné úpravy provozu - místní komunikace Lipová",
    "about": {
        "classification": [
            {
                "name": "oznámení"
            }
        ],
        "locations": [
            {
                "address": {
                    "street_address": "Lipová",
                    "locality": "Plasy",
                    "country_code": "CZ",
                    "identifiers": [
                        {
                            "identifier": "404811",
                            "scheme": "RUIAN"
                        }
                    ]
                }
            }
        ]
    },
    "url": "http://www.plasy.cz/urad-361/uredni-deska/zverejneni-stanoveni-prechodne-upravy-provozu-mistni-komunikace-lipova-1282.html",
    "media_type": "text/html",
    "documents": [
        {
            "url": "http://www.plasy.cz/e_download.php?file=data/uredni_deska/obsah1198_1.pdf&original=Stanoven%C3%AD%20p%C5%99echodn%C3%A9%20%C3%BApravy-%20Lipov%C3%A1.pdf",
            "media_type": "application/pdf"
        }
    ]
}
